import React from 'react';
import Head from 'next/head';
import Homes from './Home';
// import Navbar from './Navbar';

export default function Home() {
  return (
    <main className="d-flex flex-column min-vh-100 container" style={{ marginTop: '96px' }}>
      <Head>
        <title>Sidhu Coaching Center</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossOrigin="anonymous" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossOrigin="anonymous" />
      </Head>
      <Homes />
    </main>
  );
}
